In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName("Datetime").getOrCreate()

In [8]:
apple = spark.read.csv("AAPL_data.csv", inferSchema= True, header = True)

In [9]:
 apple.show()

+-------------------+-------+-------+-------+-------+---------+----+
|               date|   open|   high|    low|  close|   volume|Name|
+-------------------+-------+-------+-------+-------+---------+----+
|2013-02-08 00:00:00|67.7142|68.4014|66.8928|67.8542|158168416|AAPL|
|2013-02-11 00:00:00|68.0714|69.2771|67.6071|68.5614|129029425|AAPL|
|2013-02-12 00:00:00|68.5014|68.9114|66.8205|66.8428|151829363|AAPL|
|2013-02-13 00:00:00|66.7442|67.6628|66.1742|66.7156|118721995|AAPL|
|2013-02-14 00:00:00|66.3599|67.3771|66.2885|66.6556| 88809154|AAPL|
|2013-02-15 00:00:00|66.9785|67.1656|65.7028|65.7371| 97924631|AAPL|
|2013-02-19 00:00:00|65.8714|66.1042|64.8356|65.7128|108854046|AAPL|
|2013-02-20 00:00:00|65.3842|65.3842|64.1142|64.1214|118891367|AAPL|
|2013-02-21 00:00:00|63.7142|64.1671|63.2599|63.7228|111596821|AAPL|
|2013-02-22 00:00:00|64.1785|64.5142|63.7999|64.4014| 82583823|AAPL|
|2013-02-25 00:00:00|64.8356|65.0171|63.2242|63.2571| 92899597|AAPL|
|2013-02-26 00:00:00|63.4028|64.5056|62.5228|64.1385|125096657|AAPL|
|2013-02-27 00:00:00|64.0614|64.6342|62.9499|63.5099|146674682|AAPL|
|2013-02-28 00:00:00|63.4357|63.9814|63.0571|63.0571| 80532382|AAPL|
|2013-03-01 00:00:00|62.5714|62.5971|61.4257|61.4957|137899041|AAPL|
|2013-03-04 00:00:00|61.1142|61.1714|59.8571|60.0071|145406366|AAPL|
|2013-03-05 00:00:00|60.2114|62.1699|60.1071|61.5919|159298020|AAPL|
|2013-03-06 00:00:00|62.0728|62.1785|60.6328|60.8088|114903180|AAPL|
|2013-03-07 00:00:00|60.6428|61.7157|60.1514|61.5117|116992841|AAPL|
|2013-03-08 00:00:00|61.3999|62.2042|61.2299|61.6742| 97854442|AAPL|
+-------------------+-------+-------+-------+-------+---------+----+
only showing top 20 rows

In [12]:
from pyspark.sql.functions import (dayofmonth, dayofweek, month, year,
                                   weekofyear,dayofyear, hour, format_number, date_format)

In [17]:
apple.select(month("date")).show()
apple.select(year("date")).show()

+-----------+
|month(date)|
+-----------+
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          2|
|          3|
|          3|
|          3|
|          3|
|          3|
|          3|
+-----------+
only showing top 20 rows

+----------+
|year(date)|
+----------+
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
+----------+
only showing top 20 rows

In [18]:
apple.select(year("date")).show()

+----------+
|year(date)|
+----------+
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
|      2013|
+----------+
only showing top 20 rows

In [20]:
apple.select(hour(apple["date"])).show()

+----------+
|hour(date)|
+----------+
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
|         0|
+----------+
only showing top 20 rows

In [25]:
new_df= apple.withColumn("Year", year(apple["date"]))

In [26]:
new_df.show()

+-------------------+-------+-------+-------+-------+---------+----+----+
|               date|   open|   high|    low|  close|   volume|Name|Year|
+-------------------+-------+-------+-------+-------+---------+----+----+
|2013-02-08 00:00:00|67.7142|68.4014|66.8928|67.8542|158168416|AAPL|2013|
|2013-02-11 00:00:00|68.0714|69.2771|67.6071|68.5614|129029425|AAPL|2013|
|2013-02-12 00:00:00|68.5014|68.9114|66.8205|66.8428|151829363|AAPL|2013|
|2013-02-13 00:00:00|66.7442|67.6628|66.1742|66.7156|118721995|AAPL|2013|
|2013-02-14 00:00:00|66.3599|67.3771|66.2885|66.6556| 88809154|AAPL|2013|
|2013-02-15 00:00:00|66.9785|67.1656|65.7028|65.7371| 97924631|AAPL|2013|
|2013-02-19 00:00:00|65.8714|66.1042|64.8356|65.7128|108854046|AAPL|2013|
|2013-02-20 00:00:00|65.3842|65.3842|64.1142|64.1214|118891367|AAPL|2013|
|2013-02-21 00:00:00|63.7142|64.1671|63.2599|63.7228|111596821|AAPL|2013|
|2013-02-22 00:00:00|64.1785|64.5142|63.7999|64.4014| 82583823|AAPL|2013|
|2013-02-25 00:00:00|64.8356|65.0171|63.2242|63.2571| 92899597|AAPL|2013|
|2013-02-26 00:00:00|63.4028|64.5056|62.5228|64.1385|125096657|AAPL|2013|
|2013-02-27 00:00:00|64.0614|64.6342|62.9499|63.5099|146674682|AAPL|2013|
|2013-02-28 00:00:00|63.4357|63.9814|63.0571|63.0571| 80532382|AAPL|2013|
|2013-03-01 00:00:00|62.5714|62.5971|61.4257|61.4957|137899041|AAPL|2013|
|2013-03-04 00:00:00|61.1142|61.1714|59.8571|60.0071|145406366|AAPL|2013|
|2013-03-05 00:00:00|60.2114|62.1699|60.1071|61.5919|159298020|AAPL|2013|
|2013-03-06 00:00:00|62.0728|62.1785|60.6328|60.8088|114903180|AAPL|2013|
|2013-03-07 00:00:00|60.6428|61.7157|60.1514|61.5117|116992841|AAPL|2013|
|2013-03-08 00:00:00|61.3999|62.2042|61.2299|61.6742| 97854442|AAPL|2013|
+-------------------+-------+-------+-------+-------+---------+----+----+
only showing top 20 rows

In [27]:
new_df.select("Year").distinct().show()

+----+
|Year|
+----+
|2018|
|2015|
|2013|
|2014|
|2016|
|2017|
+----+

In [34]:
new = new_df.groupBy("Year").mean().select(["Year", "avg(close)"])

In [39]:
new.select(["Year", format_number("avg(close)", 2).alias("Average Closing Price")]).orderBy("Year").show()

+----+---------------------+
|Year|Average Closing Price|
+----+---------------------+
|2013|                67.24|
|2014|                92.26|
|2015|               120.04|
|2016|               104.60|
|2017|               150.59|
|2018|               171.59|
+----+---------------------+